# Generated by Django 6.0.6 on 2026-07-05 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SYSTEM_ADMIN', 'Administrador do Sistema'), ('SCHOOL_DIRECTOR', 'Diretor da Escola'), ('TEACHER', 'Professor'), ('COLLABORATOR', 'Colaborador'), ('GUARDIAN', 'Responsável'), ('STUDENT', 'Aluno')], default='COLLABORATOR', max_length=32, verbose_name='perfil de acesso')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='cargo/função')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='deve trocar senha no próximo acesso')),
                ('is_active_profile', models.BooleanField(default=True, verbose_name='perfil ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='schools.school', verbose_name='escola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuários',
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
    ]
