# Generated by Django 6.0.6 on 2026-07-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última atividade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da última atividade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_user_agent',
            field=models.TextField(blank=True, verbose_name='navegador/dispositivo da última atividade'),
        ),
    ]
