# Generated by Django 6.0.6 on 2026-07-06 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_last_activity_at_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_system_default', models.BooleanField(default=False, verbose_name='grupo padrão do sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_groups', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_groups', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'grupo de acesso',
                'verbose_name_plural': 'grupos de acesso',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=120, verbose_name='código da permissão')),
                ('allowed', models.BooleanField(default=True, verbose_name='permitido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.accessgroup', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'permissão do grupo',
                'verbose_name_plural': 'permissões do grupo',
                'ordering': ['group', 'permission_code'],
            },
        ),
        migrations.CreateModel(
            name='UserAccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='atribuído em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_access_groups', to=settings.AUTH_USER_MODEL, verbose_name='atribuído por')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.accessgroup', verbose_name='grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'grupo do usuário',
                'verbose_name_plural': 'grupos do usuário',
                'ordering': ['user', 'group'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=120, verbose_name='código da permissão')),
                ('allowed', models.BooleanField(default=True, help_text='Use permitido=True para liberar e permitido=False para bloquear uma permissão específica.', verbose_name='permitido')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='atribuído em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_permission_overrides', to=settings.AUTH_USER_MODEL, verbose_name='atribuído por')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_overrides', to='schools.school', verbose_name='escola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'permissão individual',
                'verbose_name_plural': 'permissões individuais',
                'ordering': ['user', 'permission_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='accessgroup',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_access_group_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='accessgrouppermission',
            constraint=models.UniqueConstraint(fields=('group', 'permission_code'), name='unique_permission_code_per_access_group'),
        ),
        migrations.AddConstraint(
            model_name='useraccessgroup',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_access_group'),
        ),
        migrations.AddConstraint(
            model_name='userpermissionoverride',
            constraint=models.UniqueConstraint(fields=('user', 'school', 'permission_code'), name='unique_user_permission_override_per_school'),
        ),
    ]
