# Generated by Django 6.0.6 on 2026-07-05 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Privado'), ('SCHOOL_STAFF', 'Equipe da escola'), ('TEACHERS', 'Professores'), ('GUARDIANS', 'Responsáveis'), ('PUBLIC_SCHOOL', 'Público da escola')], default='PRIVATE', max_length=30, verbose_name='visibilidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_folders', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file_manager.filefolder', verbose_name='pasta superior')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'pasta de arquivos',
                'verbose_name_plural': 'pastas de arquivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('category', models.CharField(choices=[('GENERAL', 'Geral'), ('SCHOOL_DOCUMENT', 'Documento da escola'), ('STUDENT_DOCUMENT', 'Documento de aluno'), ('TEACHER_DOCUMENT', 'Documento de professor'), ('CLASS_MATERIAL', 'Material de aula'), ('ANNOUNCEMENT', 'Comunicado'), ('POLICY', 'Política/regulamento'), ('CONTRACT', 'Contrato'), ('IMAGE', 'Imagem'), ('OTHER', 'Outro')], default='GENERAL', max_length=30, verbose_name='categoria')),
                ('file', models.FileField(upload_to='file-manager/files/', verbose_name='arquivo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Privado'), ('SCHOOL_STAFF', 'Equipe da escola'), ('TEACHERS', 'Professores'), ('GUARDIANS', 'Responsáveis'), ('PUBLIC_SCHOOL', 'Público da escola')], default='PRIVATE', max_length=30, verbose_name='visibilidade')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('ARCHIVED', 'Arquivado'), ('DELETED', 'Excluído')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='file_manager.filefolder', verbose_name='pasta')),
                ('related_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_files', to='classes.schoolclass', verbose_name='turma relacionada')),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_files', to='students.student', verbose_name='aluno relacionado')),
                ('related_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_files', to='teachers.teacher', verbose_name='professor relacionado')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_files', to='schools.school', verbose_name='escola')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_managed_files', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'arquivo gerenciado',
                'verbose_name_plural': 'arquivos gerenciados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_download', models.BooleanField(default=True, verbose_name='pode baixar')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_shares', to=settings.AUTH_USER_MODEL, verbose_name='compartilhado por')),
                ('shared_with_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_file_shares', to=settings.AUTH_USER_MODEL, verbose_name='compartilhado com')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='file_manager.managedfile', verbose_name='arquivo')),
            ],
            options={
                'verbose_name': 'compartilhamento de arquivo',
                'verbose_name_plural': 'compartilhamentos de arquivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='filefolder',
            constraint=models.UniqueConstraint(fields=('school', 'parent', 'name'), name='unique_file_folder_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='fileshare',
            constraint=models.UniqueConstraint(fields=('file', 'shared_with_user'), name='unique_file_share_per_user'),
        ),
    ]
