# Generated by Django 6.0.6 on 2026-07-06 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('body', models.TextField(verbose_name='mensagem')),
                ('audience', models.CharField(choices=[('school', 'Toda a escola'), ('class', 'Turma'), ('student', 'Aluno'), ('guardian', 'Responsável'), ('teacher', 'Professor'), ('staff', 'Equipe interna'), ('custom', 'Personalizado')], default='custom', max_length=30, verbose_name='público')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('archived', 'Arquivada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='status')),
                ('requires_read_confirmation', models.BooleanField(default=False, verbose_name='exige confirmação de leitura')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='arquivada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='schools.school', verbose_name='escola')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='remetente')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='status')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('first_read_at', models.DateTimeField(blank=True, null=True, verbose_name='primeira leitura em')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='última leitura em')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de leituras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.message', verbose_name='mensagem')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_recipients', to='students.student', verbose_name='aluno relacionado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='usuário destinatário')),
            ],
            options={
                'verbose_name': 'destinatário da mensagem',
                'verbose_name_plural': 'destinatários da mensagem',
                'ordering': ['message', 'user'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='lido em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='navegador/dispositivo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_read_receipts', to=settings.AUTH_USER_MODEL, verbose_name='lido por')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='communications.messagerecipient', verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'comprovante de leitura',
                'verbose_name_plural': 'comprovantes de leitura',
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['school', 'status', 'created_at'], name='communicati_school__d48a79_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['school', 'audience', 'created_at'], name='communicati_school__e257ef_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='communicati_sender__7da57d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['priority', 'created_at'], name='communicati_priorit_625eba_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['user', 'status', 'created_at'], name='communicati_user_id_c04094_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['message', 'status'], name='communicati_message_eae792_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['student', 'created_at'], name='communicati_student_60044b_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagerecipient',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'student'), name='unique_message_recipient_user_student'),
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['recipient', 'read_at'], name='communicati_recipie_06fd27_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['read_by', 'read_at'], name='communicati_read_by_9f6aef_idx'),
        ),
    ]
