# Generated by Django 6.0.6 on 2026-07-05 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('preferred_name', models.CharField(blank=True, max_length=120, verbose_name='nome de exibição')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='RA/matrícula')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='CPF/RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('gender', models.CharField(choices=[('FEMALE', 'Feminino'), ('MALE', 'Masculino'), ('OTHER', 'Outro'), ('NOT_INFORMED', 'Não informado')], default='NOT_INFORMED', max_length=20, verbose_name='gênero')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do aluno')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone do aluno')),
                ('current_grade', models.CharField(blank=True, help_text='Exemplo: 5º ano, 1º ano EM, Infantil II.', max_length=80, verbose_name='série/ano atual')),
                ('current_shift', models.CharField(blank=True, help_text='Exemplo: Manhã, Tarde, Integral.', max_length=80, verbose_name='turno atual')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('TRANSFERRED', 'Transferido'), ('GRADUATED', 'Concluído'), ('SUSPENDED', 'Suspenso')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='data de matrícula')),
                ('zip_code', models.CharField(blank=True, max_length=16, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=220, verbose_name='endereço')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('has_medical_condition', models.BooleanField(default=False, verbose_name='possui condição médica')),
                ('medical_condition_notes', models.TextField(blank=True, verbose_name='observações médicas')),
                ('has_allergy', models.BooleanField(default=False, verbose_name='possui alergia')),
                ('allergy_notes', models.TextField(blank=True, verbose_name='observações sobre alergias')),
                ('uses_medication', models.BooleanField(default=False, verbose_name='usa medicamento contínuo')),
                ('medication_notes', models.TextField(blank=True, verbose_name='observações sobre medicamentos')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=180, verbose_name='contato de emergência')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32, verbose_name='telefone de emergência')),
                ('image_use_authorized', models.BooleanField(default=False, help_text='Autorização do responsável para uso de imagem conforme política da escola.', verbose_name='uso de imagem autorizado')),
                ('exit_authorized', models.BooleanField(default=False, help_text='Indica se o aluno possui autorização registrada para saída conforme regras da escola.', verbose_name='saída autorizada')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('BIRTH_CERTIFICATE', 'Certidão de nascimento'), ('VACCINATION_CARD', 'Carteira de vacinação'), ('SCHOOL_RECORD', 'Histórico escolar'), ('MEDICAL_REPORT', 'Laudo médico'), ('AUTHORIZATION', 'Autorização'), ('OTHER', 'Outro')], default='OTHER', max_length=30, verbose_name='tipo de documento')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('file', models.FileField(upload_to='students/documents/', verbose_name='arquivo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='aluno')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'documento do aluno',
                'verbose_name_plural': 'documentos dos alunos',
                'ordering': ['student__full_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('relationship', models.CharField(choices=[('MOTHER', 'Mãe'), ('FATHER', 'Pai'), ('GRANDMOTHER', 'Avó'), ('GRANDFATHER', 'Avô'), ('AUNT', 'Tia'), ('UNCLE', 'Tio'), ('LEGAL_GUARDIAN', 'Responsável legal'), ('OTHER', 'Outro')], default='LEGAL_GUARDIAN', max_length=30, verbose_name='parentesco')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='CPF/RG')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('is_primary', models.BooleanField(default=False, verbose_name='responsável principal')),
                ('can_pick_up_student', models.BooleanField(default=False, verbose_name='autorizado a retirar o aluno')),
                ('receives_notifications', models.BooleanField(default=True, verbose_name='recebe comunicados')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student', verbose_name='aluno')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário usado para login do responsável no PortalK12, quando houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_guardian_profiles', to=settings.AUTH_USER_MODEL, verbose_name='usuário de acesso')),
            ],
            options={
                'verbose_name': 'responsável do aluno',
                'verbose_name_plural': 'responsáveis dos alunos',
                'ordering': ['-is_primary', 'full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('school', 'registration_number'), name='unique_student_registration_per_school'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('document', ''), _negated=True), fields=('school', 'document'), name='unique_student_document_per_school'),
        ),
    ]
