# Generated by Django 6.0.6 on 2026-07-05 16:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING', 'Pendente'), ('PAID', 'Pago'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('CASH', 'Dinheiro'), ('PIX', 'Pix'), ('CARD', 'Cartão'), ('SCHOOL_CREDIT', 'Crédito escolar'), ('OTHER', 'Outro')], default='OTHER', max_length=30, verbose_name='forma de pagamento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cafeteria_orders', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('responsible_guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafeteria_orders', to='students.studentguardian', verbose_name='responsável')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_orders', to='schools.school', verbose_name='escola')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafeteria_orders', to='students.student', verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'pedido da cantina',
                'verbose_name_plural': 'pedidos da cantina',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='código/SKU')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='preço')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='custo')),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='estoque atual')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='estoque mínimo')),
                ('unit', models.CharField(default='un', help_text='Exemplo: un, kg, pacote, copo.', max_length=30, verbose_name='unidade')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafeteria/products/', verbose_name='imagem')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('OUT_OF_STOCK', 'Sem estoque')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('is_restricted', models.BooleanField(default=False, help_text='Use para produtos que exigem controle da escola ou autorização do responsável.', verbose_name='produto restrito')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cafeteria_products', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_products', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'produto da cantina',
                'verbose_name_plural': 'produtos da cantina',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='preço unitário')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafeteria.cafeteriaorder', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='cafeteria.cafeteriaproduct', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item do pedido da cantina',
                'verbose_name_plural': 'itens dos pedidos da cantina',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_product_categories', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'categoria de produto da cantina',
                'verbose_name_plural': 'categorias de produtos da cantina',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cafeteriaproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='cafeteria.cafeteriaproductcategory', verbose_name='categoria'),
        ),
        migrations.AddConstraint(
            model_name='cafeteriaproductcategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_cafeteria_category_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='cafeteriaproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('school', 'sku'), name='unique_cafeteria_product_sku_per_school'),
        ),
        migrations.AddConstraint(
            model_name='cafeteriaproduct',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_cafeteria_product_name_per_school'),
        ),
    ]
