# Generated by Django 6.0.6 on 2026-07-06 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=80, verbose_name='perfil do usuário')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('deleted', 'Excluído'), ('restored', 'Restaurado'), ('login_success', 'Login realizado'), ('login_failed', 'Falha de login'), ('logout', 'Logout'), ('permission_granted', 'Permissão concedida'), ('permission_revoked', 'Permissão removida'), ('role_changed', 'Perfil alterado'), ('message_sent', 'Mensagem enviada'), ('message_read', 'Mensagem lida'), ('file_uploaded', 'Arquivo enviado'), ('file_deleted', 'Arquivo excluído'), ('other', 'Outra ação')], default='other', max_length=80, verbose_name='ação')),
                ('module', models.CharField(blank=True, max_length=80, verbose_name='módulo')),
                ('object_type', models.CharField(blank=True, max_length=120, verbose_name='tipo do registro')),
                ('object_id', models.CharField(blank=True, max_length=120, verbose_name='id do registro')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='representação do registro')),
                ('changes_before', models.JSONField(blank=True, default=dict, verbose_name='dados anteriores')),
                ('changes_after', models.JSONField(blank=True, default=dict, verbose_name='dados novos')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='navegador/dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuário responsável')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'created_at'], name='auditlog_au_school__5b48a9_idx'), models.Index(fields=['actor_user', 'created_at'], name='auditlog_au_actor_u_08d67b_idx'), models.Index(fields=['action', 'created_at'], name='auditlog_au_action_403129_idx'), models.Index(fields=['module', 'created_at'], name='auditlog_au_module_abc67c_idx'), models.Index(fields=['object_type', 'object_id'], name='auditlog_au_object__23a8a1_idx')],
            },
        ),
    ]
