# Generated by Django 6.0.6 on 2026-07-05 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('preferred_name', models.CharField(blank=True, max_length=120, verbose_name='nome de exibição')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='CPF/RG')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='matrícula funcional')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('department', models.CharField(choices=[('ADMINISTRATION', 'Administrativo'), ('SECRETARIAT', 'Secretaria'), ('COORDINATION', 'Coordenação'), ('INSPECTION', 'Inspetoria'), ('CAFETERIA', 'Cantina'), ('CLEANING', 'Limpeza'), ('SECURITY', 'Segurança'), ('MAINTENANCE', 'Manutenção'), ('TRANSPORT', 'Transporte'), ('IT', 'Tecnologia'), ('OTHER', 'Outro')], default='OTHER', max_length=30, verbose_name='setor')),
                ('job_title', models.CharField(help_text='Exemplo: Secretária, Inspetor, Auxiliar de limpeza, Porteiro.', max_length=120, verbose_name='cargo/função')),
                ('contract_type', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('TEMPORARY', 'Temporário'), ('INTERN', 'Estagiário'), ('OUTSOURCED', 'Terceirizado'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='tipo de contrato')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='data de desligamento')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('ON_LEAVE', 'Afastado')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('can_access_system', models.BooleanField(default=False, help_text='Marque se este colaborador terá login no PortalK12.', verbose_name='pode acessar o sistema')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaborators', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='schools.school', verbose_name='escola')),
                ('user', models.OneToOneField(blank=True, help_text='Usuário usado para login do colaborador no PortalK12, quando houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborator_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário de acesso')),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'ordering': ['full_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('school', 'registration_number'), name='unique_collaborator_registration_per_school'), models.UniqueConstraint(condition=models.Q(('document', ''), _negated=True), fields=('school', 'document'), name='unique_collaborator_document_per_school')],
            },
        ),
    ]
