# Generated by Django 6.0.6 on 2026-07-05 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborators', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('document_type', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('CNH', 'CNH'), ('PASSPORT', 'Passaporte'), ('COMPANY_BADGE', 'Crachá da empresa'), ('OTHER', 'Outro')], default='CPF', max_length=30, verbose_name='tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='número do documento')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('company_name', models.CharField(blank=True, help_text='Use para prestadores de serviço, entregadores, fornecedores ou visitantes corporativos.', max_length=180, verbose_name='empresa/organização')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/photos/', verbose_name='foto do visitante')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('BLOCKED', 'Bloqueado'), ('WATCHLIST', 'Atenção')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visitors', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'visitante',
                'verbose_name_plural': 'visitantes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('MEETING', 'Reunião'), ('STUDENT_PICKUP', 'Retirada de aluno'), ('STUDENT_DROPOFF', 'Entrega de aluno'), ('SERVICE_PROVIDER', 'Prestador de serviço'), ('DELIVERY', 'Entrega'), ('EVENT', 'Evento'), ('INTERVIEW', 'Entrevista'), ('OTHER', 'Outro')], default='OTHER', max_length=30, verbose_name='motivo da visita')),
                ('purpose_description', models.CharField(blank=True, help_text='Exemplo: reunião com coordenação, manutenção do portão, retirada autorizada.', max_length=220, verbose_name='descrição do motivo')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='data/hora agendada')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='entrada em')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='saída em')),
                ('badge_number', models.CharField(blank=True, max_length=40, verbose_name='número do crachá')),
                ('vehicle_plate', models.CharField(blank=True, help_text='Use apenas quando a escola controlar acesso de veículos.', max_length=20, verbose_name='placa do veículo')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('CHECKED_IN', 'Entrada registrada'), ('CHECKED_OUT', 'Saída registrada'), ('CANCELLED', 'Cancelada'), ('DENIED', 'Negada')], default='SCHEDULED', max_length=20, verbose_name='status da visita')),
                ('denial_reason', models.TextField(blank=True, verbose_name='motivo da negativa')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_visits', to=settings.AUTH_USER_MODEL, verbose_name='autorizado por')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_visits', to=settings.AUTH_USER_MODEL, verbose_name='entrada registrada por')),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_visits', to=settings.AUTH_USER_MODEL, verbose_name='saída registrada por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('host_collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visits', to='collaborators.collaborator', verbose_name='colaborador visitado')),
                ('host_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visits', to='teachers.teacher', verbose_name='professor visitado')),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_visits', to='students.student', verbose_name='aluno relacionado')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='schools.school', verbose_name='escola')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitors.visitor', verbose_name='visitante')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('document_type', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('CNH', 'CNH'), ('PASSPORT', 'Passaporte'), ('COMPANY_BADGE', 'Crachá da empresa'), ('OTHER', 'Outro')], default='OTHER', max_length=30, verbose_name='tipo de documento')),
                ('file', models.FileField(upload_to='visitors/documents/', verbose_name='arquivo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_visitor_documents', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visitors.visitor', verbose_name='visitante')),
            ],
            options={
                'verbose_name': 'documento do visitante',
                'verbose_name_plural': 'documentos dos visitantes',
                'ordering': ['visitor__full_name', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='visitor',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('school', 'document_type', 'document_number'), name='unique_visitor_document_per_school'),
        ),
    ]
