# Generated by Django 6.0.6 on 2026-07-05 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemplo: Ano letivo 2026.', max_length=80, verbose_name='nome')),
                ('year', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('status', models.CharField(choices=[('PLANNED', 'Planejado'), ('ACTIVE', 'Ativo'), ('CLOSED', 'Encerrado'), ('ARCHIVED', 'Arquivado')], default='PLANNED', max_length=20, verbose_name='status')),
                ('is_current', models.BooleanField(default=False, verbose_name='ano letivo atual')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'ano letivo',
                'verbose_name_plural': 'anos letivos',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemplo: Sala 01, Laboratório Maker, Sala Infantil A.', max_length=80, verbose_name='nome da sala')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='capacidade')),
                ('location', models.CharField(blank=True, help_text='Exemplo: Bloco A, 2º andar.', max_length=120, verbose_name='localização')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'sala de aula',
                'verbose_name_plural': 'salas de aula',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemplo: 5º Ano A, Infantil II B, 1º EM Robótica.', max_length=120, verbose_name='nome da turma')),
                ('grade', models.CharField(blank=True, help_text='Exemplo: 5º ano, Infantil II, 1º ano EM.', max_length=80, verbose_name='série/ano')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código da turma')),
                ('max_students', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='limite de alunos')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('CLOSED', 'Encerrada')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.academicyear', verbose_name='ano letivo')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classes.classroom', verbose_name='sala de aula')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_classes', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('responsible_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_classes', to='teachers.teacher', verbose_name='professor responsável')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['academic_year__year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='data de entrada')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='data de saída')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('TRANSFERRED', 'Transferido'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Concluído')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='students.student', verbose_name='aluno')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.schoolclass', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'matrícula em turma',
                'verbose_name_plural': 'matrículas em turmas',
                'ordering': ['school_class__name', 'student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemplo: Manhã, Tarde, Integral.', max_length=80, verbose_name='nome')),
                ('shift_type', models.CharField(choices=[('MORNING', 'Manhã'), ('AFTERNOON', 'Tarde'), ('EVENING', 'Noite'), ('FULL_TIME', 'Integral'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='tipo de turno')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='horário de início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='horário de término')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.shift', verbose_name='turno'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'year', 'name'), name='unique_academic_year_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_classroom_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('school', 'code'), name='unique_classroom_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.UniqueConstraint(fields=('school_class', 'student'), name='unique_student_per_class'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_shift_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='unique_class_name_per_school_year'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('school', 'academic_year', 'code'), name='unique_class_code_per_school_year'),
        ),
    ]
