# Generated by Django 6.0.6 on 2026-07-05 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('preferred_name', models.CharField(blank=True, max_length=120, verbose_name='nome de exibição')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='CPF/RG')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='matrícula funcional')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('main_subject', models.CharField(blank=True, max_length=120, verbose_name='disciplina principal')),
                ('subjects', models.CharField(blank=True, help_text='Exemplo: Matemática, Física, Robótica.', max_length=255, verbose_name='disciplinas')),
                ('contract_type', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('TEMPORARY', 'Temporário'), ('INTERN', 'Estagiário'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='tipo de contrato')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('ON_LEAVE', 'Afastado')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teachers', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school', verbose_name='escola')),
                ('user', models.OneToOneField(blank=True, help_text='Usuário usado para login do professor no PortalK12.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário de acesso')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('TECHNICAL', 'Técnico'), ('UNDERGRADUATE', 'Graduação'), ('SPECIALIZATION', 'Especialização'), ('MBA', 'MBA'), ('MASTER', 'Mestrado'), ('DOCTORATE', 'Doutorado'), ('POST_DOCTORATE', 'Pós-doutorado'), ('OTHER', 'Outro')], default='UNDERGRADUATE', max_length=30, verbose_name='nível')),
                ('course_name', models.CharField(max_length=180, verbose_name='curso/formação')),
                ('institution', models.CharField(blank=True, max_length=180, verbose_name='instituição')),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano de início')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano de conclusão')),
                ('is_completed', models.BooleanField(default=True, verbose_name='concluído')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='teachers/education/', verbose_name='certificado/diploma')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='teachers.teacher', verbose_name='professor')),
            ],
            options={
                'verbose_name': 'formação do professor',
                'verbose_name_plural': 'formações dos professores',
                'ordering': ['-end_year', 'level', 'course_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('school', 'registration_number'), name='unique_teacher_registration_per_school'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('document', ''), _negated=True), fields=('school', 'document'), name='unique_teacher_document_per_school'),
        ),
    ]
