# Generated by Django 6.0.6 on 2026-07-05 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nome da escola')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('legal_name', models.CharField(blank=True, max_length=180, verbose_name='razão social')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('zip_code', models.CharField(blank=True, max_length=16, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=220, verbose_name='endereço')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('SUSPENDED', 'Suspensa')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_schools', to=settings.AUTH_USER_MODEL, verbose_name='diretor responsável')),
            ],
            options={
                'verbose_name': 'escola',
                'verbose_name_plural': 'escolas',
                'ordering': ['name'],
            },
        ),
    ]
